---
title: "Titanic Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
df <- read.csv("E:\\data-science\\GCS training session\\titanic\\titanic.csv",stringsAsFactors = FALSE)
df$sex <- as.factor(df$sex)
df$pclass <- as.factor(df$pclass)
df$survived <- as.factor(df$survived)
df$embarked <- as.factor(df$embarked)
prop.table(table(df$survived))
```

Column {data-width=340}
-----------------------------------------------------------------------

### Survival Count

```{r}
ggplot(df, aes(x = survived)) + theme_classic() +
  geom_bar(fill='blue') +
  labs(y = "Passenger count",title = "Titanic survived count")

```

Column {data-width=330}
-----------------------------------------------------------------------

### Survival by gender

```{r}
ggplot(df, aes(x = sex,fill = survived)) + theme_classic() +
  geom_bar() +
  labs(y = "Passenger count",title = "Survival count by gender")

```

### survival based on class

```{r}
ggplot(df, aes(x = pclass,fill = survived)) + theme_classic() +
  geom_bar() +
  labs(y = "Passenger count",title = "Survival count by class")

```

Column {data-width=330}
-----------------------------------------------------------------------

### titanic survival count by class & gender

```{r}
ggplot(df, aes(x = sex,fill = survived)) + theme_light() +
  facet_grid(~pclass) +
  geom_bar() +
  labs(y = "Passenger count",title = "Titanic Survival count by class & gender")

```

### survival ratio in each class

```{r}
ggplot(df,aes(x="",fill = survived)) +
  geom_bar(position = "fill") +
  facet_grid(~pclass) + coord_polar(theta = "y")

```
